### ISSUE TITLE
make it right click

### ISSUE THREAD

**Issue by huhuhuhuhhu** [HackerHansen/Zombsroyale.io-Aimbot-BETA#7]

**Comment by huhuhuhuhhu** [comment]
no right click

**Comment by huhuhuhuhhu** [comment]
file:///Users/alipiazza/Downloads/zombsroyaleio-hack-master/manifest.json

**Comment by huhuhuhuhhu** [comment]
file:///Users//Downloads/zombsroyaleio-hack-master/manifest.json

**Comment by HackerHansen** [comment]
Sorry I just saw the issue now. 

**Bruh just change the target key its literally in the menu. Change the key to RButton**
